name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 'Build:dockerimage'
      uses: docker/build-push-action@v1
      with:
          registry: ghcr.io
          username: "miromasat"
          password: ${{ secrets.PAT }}
          repository: miromasat/super-octo-telegram
          tags: latest
    
    
